### ISSUE TITLE
Looks good, how can I use it?

### ISSUE THREAD

**Issue by jonagoldman** [mlanin/laravel-api-debugger#1]
Tried to use this, but no idea how. How to attach log to JSON response?

**Comment by mlanin** [comment]
@jonagoldman you mean sql log?

**Comment by jonagoldman** [comment]
Yes, how to do what you show in the readme. Basically add `"debug": { //some data }` to the JSON response of my API.

**Comment by mlanin** [comment]
Have you done everything written in the readme? Especially in the **Installation** section?

**Comment by jonagoldman** [comment]
Yes.
1) get package 2) register service provider 3) add alias.

From what I read in the **_Debugging**_ section (I assume this is the "Usage" section), there is only one method: `Debugger::dump($foo, $bar);` where `$foo` is a string and `$bar` an array. That's nice, but how do I get the SQL queries into my JSON response? How does that `dump()` method comes into play?

**Comment by mlanin** [comment]
Check please if your `APP_DEBUG` set to `true`. And what Laravel version do you use?

`Debugger::dump();` method can receive any number of variables to dump. And they will be passed to `debug.dump` json attribute in the output.

**Comment by mlanin** [comment]
Also can you please show me how you return data from your controller?

**Comment by marceux** [comment]
I'm having the same issue. As of right now, I'm returning Models directly in my controllers

**Comment by mlanin** [comment]
@marceux that's the problem. Your controller methods have to return `JsonResponse` object in order to let package know that you are returning real JSON and not anything else. 

So just use `response()->json(['models' => [$model,...]]);`.

**Comment by ivanlolivier** [comment]
I have the same problem. The service provider is running but the debug section is not been added.
I'm using dingo. Is this a knowed problem?

**Comment by mlanin** [comment]
@ivanlolivier what kind of response do you return in your controller method?

**Comment by ivanlolivier** [comment]
@mlanin First of all thanks for the response.

I'm using this:
`return $this->response->item(User::findOrFail($id), new UserTransformer);`

but also tried with:

`response()->json(User::findOrFail($id))`

and

`response()->json(['user' => User::findOrFail($id)])`

**Comment by mlanin** [comment]
@ivanlolivier you have to return JsonResponse object. The easiest way to do it is to return `response()->json(['data' => ... ])`.

What Laravel version do you use and check please that `APP_DEBUG` is set to `true`.

**Comment by ivanlolivier** [comment]
The `APP_DEBUG` is already in true and I'm using `laravel 5.2.`

I'm going to try responding in that way. Thanks!

**Comment by Andreyco** [comment]
From my observations, debug data is appended to response when request is executed from browser. Response returned after request is made from Postman/Insomnia does not contain debug data. I suppose this is the case for any other REST client.

**Comment by alvincrisuy** [comment]
@mlanin How can I make it work in 5.4?

**Comment by mlanin** [comment]
@alvincrisuy you can use ^0.2.0 version

**Comment by mlanin** [comment]
@alvincrisuy My bad. In 5.4 events system was slightly changed. I'll update to 5.4 soon.

**Comment by mlanin** [comment]
@alvincrisuy released a version for 5.4. You can use it now! ;)

**Comment by jonagoldman** [comment]
now its working for me

**Comment by mlanin** [comment]
@jonagoldman good luck in debugging! :)
