### ISSUE TITLE
Model name of database query

### ISSUE THREAD

**Issue by hiranipradeep** [mlanin/laravel-api-debugger#11]
Thanks for making this debugger tool.

I want to display the 'model' (query running from particular model) parameter name like this:

  ```
"debug": {
        "database": {
            "total": 5,
            "items": [
                {  
                    "model": "App\User",
                    "connection": "mysql",
                    "query": "select * from `ta_users`;",
                    "time": 106.27
                },
            ]
        }
   }
```

Please help me with this additional parameter.
Thanks

**Comment by mlanin** [comment]
Unfortunately it is impossible :( Laravel doesn't send model name in `query` event
