### ISSUE TITLE
is there any way to return mongodb query in response?

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [mlanin/laravel-api-debugger#12]
My api app use both mysql and mongo and i use https://github.com/jenssegers/laravel-mongodb for mongodb eloquent, i want to know that can i get mongo query in response or should i use other package?

**Comment by LucasLeandro1204** [comment]
You can create a mongodb query collection, then add it to config https://github.com/mlanin/laravel-api-debugger/blob/master/config/api-debugger.php
