### ISSUE TITLE
PHP 7.4 error: "Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by amcsi** [mlanin/laravel-api-debugger#22]
This is somewhat related to #4, but not quite.

I think this issue is caused by:

https://wiki.php.net/rfc/tostring_exceptions

> Additionally convert the “could not be converted to string” and “__toString() must return a string value” recoverable fatal errors into proper Error exceptions, in line with the error policy established in PHP 7.

**Comment by vaail** [comment]
Fixed by PR #23

**Comment by gabi85ro** [comment]
Could the fix from @vaail be merged into the master branch, please

**Comment by Mehrdad-Dadkhah** [comment]
same issue

**Comment by mtx-z** [comment]
Same issue with `^3.0` Laravel 7 on PHP 7.4.4

**Comment by slamgundam** [comment]
Same issue with ^3.0 Laravel 7 on PHP 7.4.5

**Comment by gfernandez-me** [comment]
same problem here

**Comment by amcsi** [comment]
This is fixed with v4.0.0. Closing.
