### ISSUE TITLE
Don't work with jenssegers/laravel-mongodb

### ISSUE THREAD

**Issue by darkin1** [mlanin/laravel-api-debugger#3]
Like in topic, queries didn't show using jenssegers/mongodb

**Comment by mlanin** [comment]
@darkin1 I know. This is a common problem. Still trying to fix it

**Comment by mlanin** [comment]
@darkin1 Fixed in 0.2.2 release

**Comment by darkin1** [comment]
Could you show query without backslach?

![debug](https://cloud.githubusercontent.com/assets/1249151/18053562/5e3fef62-6e00-11e6-9634-b49dd9e70952.png)

![debug_raw](https://cloud.githubusercontent.com/assets/1249151/18053552/560df410-6e00-11e6-8373-95d5145e6ae1.png)

**Comment by mlanin** [comment]
Alas, but it is a limitation of json. Json accepts only double quotes and here is a json inside a json. That's why it's quotes should be escaped. There is no obvious decision how to get rid of the backslash.
