### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by jonagoldman** [mlanin/laravel-api-debugger#4]
```
FatalErrorException in QueriesCollection.php line 73:
Object of class DateTime could not be converted to string
```
this happens when using Laravel's Passport to generate tokens. The tokens are inserted into db as DateTime and it seems there are problems when doing
```
$query = vsprintf(str_replace(['%', '?'], ['%%', "'%s'"], $query), $attributes) . ';';
```

![capture](https://cloud.githubusercontent.com/assets/1297559/25318291/e23d3512-2850-11e7-8002-738347631d9f.PNG)

you can see in the attached screenshot that $atributes[5] and $atributes[6] are of type DateTime..

**Comment by mlanin** [comment]
Thanks for report, I'll try to fix it somehow...

**Comment by mlanin** [comment]
Fixed in 0.3.1. Update please.

**Comment by jonagoldman** [comment]
working for me now. thanks!

**Comment by hendisantika** [comment]
I have same issue like @jonagoldman .
I am using php 7.4 & Laravel 7.9.1.
Any suggestion??
```
<!DOCTYPE html>
<!--


Symfony\Component\Debug\Exception\FatalThrowableError: Object of class DateTime could not be converted to string in file /Users/hendisantika/Documents/freelance/dvoretsky/scrubber-backend/vendor/lanin/laravel-api-debugger/src/Collections/QueriesCollection.php on line 120
Stack trace:
  1. Symfony\Component\Debug\Exception\FatalThrowableError-&gt;() /Users/hendisantika/Documents/App/Project/vendor/lanin/laravel-api-debugger/src/Collections/QueriesCollection.php:120
  2. {main}() /Users/hendisantika/Documents/App/Project/scrubber-backend/server.php:0


```

**Comment by hendisantika** [comment]
BTW, can you show me how to set debugger in PhpStorm @jonagoldman ???

**Comment by jonagoldman** [comment]
@hendisantika this issue is 3 years old, not longer using PhpStorm. But there are a lot of articles around on how to configure the debugger.
